//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Regon {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Regon.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem aplikacyjny, brak wystaracajacej iplementacji w ramch klasy.
        /// </summary>
        internal static string App_NotImplemented {
            get {
                return ResourceManager.GetString("App_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem z deserializacja.
        /// </summary>
        internal static string AppProblem_Deserialization {
            get {
                return ResourceManager.GetString("AppProblem_Deserialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podmiot osoby fizycznej prowadzącej działalność gospodarczą.
        /// </summary>
        internal static string DaneSzukajResponse_F {
            get {
                return ResourceManager.GetString("DaneSzukajResponse_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednostka lokalna podmiotu osoby fizycznej.
        /// </summary>
        internal static string DaneSzukajResponse_LF {
            get {
                return ResourceManager.GetString("DaneSzukajResponse_LF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednostka lokalna osoby prawnej.
        /// </summary>
        internal static string DaneSzukajResponse_LP {
            get {
                return ResourceManager.GetString("DaneSzukajResponse_LP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osoba prawna / Jednostka organizacyjna niemająca osobowości prawnej.
        /// </summary>
        internal static string DaneSzukajResponse_P {
            get {
                return ResourceManager.GetString("DaneSzukajResponse_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konieczne jest pobranie i sprawdzenie kodu Captcha (metody PobierzCaptcha i SprawdzCaptcha)..
        /// </summary>
        internal static string GetValue_KomunikatKod_Captcha {
            get {
                return ResourceManager.GetString("GetValue_KomunikatKod_Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak uprawnień do raportu..
        /// </summary>
        internal static string GetValue_KomunikatKod_Forbidden {
            get {
                return ResourceManager.GetString("GetValue_KomunikatKod_Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono podmiotów..
        /// </summary>
        internal static string GetValue_KomunikatKod_NotFound {
            get {
                return ResourceManager.GetString("GetValue_KomunikatKod_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do metody DaneSzukaj przekazano zbyt wiele identyfikatorów..
        /// </summary>
        internal static string GetValue_KomunikatKod_TooManyIds {
            get {
                return ResourceManager.GetString("GetValue_KomunikatKod_TooManyIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak sesji. Sesja wygasła lub przekazano nieprawidłową wartość nagłówka sid..
        /// </summary>
        internal static string GetValue_KomunikatKod_UnAuthorize {
            get {
                return ResourceManager.GetString("GetValue_KomunikatKod_UnAuthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostepna.
        /// </summary>
        internal static string GetValue_StatusUslugi_Dostepna {
            get {
                return ResourceManager.GetString("GetValue_StatusUslugi_Dostepna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niedostepna.
        /// </summary>
        internal static string GetValue_StatusUslugi_Niedostepna {
            get {
                return ResourceManager.GetString("GetValue_StatusUslugi_Niedostepna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przerwa Techniczna.
        /// </summary>
        internal static string GetValue_StatusUslugi_PrzerwaTechniczna {
            get {
                return ResourceManager.GetString("GetValue_StatusUslugi_PrzerwaTechniczna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KRS zawiera tylko 10 cyfr.
        /// </summary>
        internal static string Invalid_Krs {
            get {
                return ResourceManager.GetString("Invalid_Krs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP zawiera tylko 10 cyfr.
        /// </summary>
        internal static string Invalid_Nip {
            get {
                return ResourceManager.GetString("Invalid_Nip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGON zawiera 9 lub 14 cyfr.
        /// </summary>
        internal static string Invalid_Regon {
            get {
                return ResourceManager.GetString("Invalid_Regon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klucz nie może byc pusty.
        /// </summary>
        internal static string Invalid_UserKey {
            get {
                return ResourceManager.GetString("Invalid_UserKey", resourceCulture);
            }
        }
    }
}
