// <auto-generated />
using System;
using Infrastructure.DatabaseRelational;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MyPlatformMsSqlDbContext))]
    [Migration("20250108015533_Third")]
    partial class Third
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Application.DatabaseRelational.Models.Addresses.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ApartmentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<int?>("StreetId")
                        .HasColumnType("int");

                    b.HasKey("AddressId")
                        .HasName("Address_pk");

                    b.HasIndex("DivisionId");

                    b.HasIndex("StreetId");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("Application.DatabaseRelational.Models.Addresses.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CountryId")
                        .HasName("Country_pk");

                    b.ToTable("Country", (string)null);
                });

            modelBuilder.Entity("Application.DatabaseRelational.Models.Addresses.Division", b =>
                {
                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("DivisionTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentDivisionId")
                        .HasColumnType("int");

                    b.Property<string>("ParentsPath")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.HasKey("DivisionId")
                        .HasName("Division_pk");

                    b.HasIndex("CountryId");

                    b.HasIndex("DivisionTypeId");

                    b.HasIndex("ParentDivisionId");

                    b.ToTable("Division", (string)null);
                });

            modelBuilder.Entity("Application.DatabaseRelational.Models.Addresses.DivisionType", b =>
                {
                    b.Property<int>("DivisionTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DivisionTypeId")
                        .HasName("DivisionType_pk");

                    b.ToTable("DivisionType", (string)null);
                });

            modelBuilder.Entity("Application.DatabaseRelational.Models.Addresses.Street", b =>
                {
                    b.Property<int>("StreetId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int?>("DivisionTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StreetId")
                        .HasName("Street_pk");

                    b.HasIndex("CountryId");

                    b.HasIndex("DivisionTypeId");

                    b.ToTable("Street", (string)null);
                });

            modelBuilder.Entity("Application.DatabaseRelational.Models.HighSchools.Institutions.AINameHistory", b =>
                {
                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.HasKey("InstitutionId", "Date")
                        .HasName("AINameHistory_pk");

                    b.ToTable("AINameHistory", (string)null);
                });

            modelBuilder.Entity("Application.DatabaseRelational.Models.HighSchools.Institutions.AISpecificType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("AISpecificType_pk");

                    b.ToTable("AISpecificType", (string)null);
                });

            modelBuilder.Entity("Application.DatabaseRelational.Models.HighSchools.Institutions.AISpecificTypeHistory", b =>
                {
                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.HasKey("InstitutionId", "TypeId", "Date")
                        .HasName("AISpecificTypeHistory_pk");

                    b.HasIndex("TypeId");

                    b.ToTable("AISpecificTypeHistory", (string)null);
                });

            modelBuilder.Entity("Application.DatabaseRelational.Models.HighSchools.Institutions.AIStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("AIStatus_pk");

                    b.ToTable("AIStatus", (string)null);
                });

            modelBuilder.Entity("Application.DatabaseRelational.Models.HighSchools.Institutions.AIStatusHistory", b =>
                {
                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.HasKey("InstitutionId", "StatusId", "Date")
                        .HasName("AIStatusHistory_pk");

                    b.HasIndex("StatusId");

                    b.ToTable("AIStatusHistory", (string)null);
                });

            modelBuilder.Entity("Application.DatabaseRelational.Models.HighSchools.Institutions.AIType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsSchool")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("AIType_pk");

                    b.ToTable("AIType", (string)null);
                });

            modelBuilder.Entity("Application.DatabaseRelational.Models.HighSchools.Institutions.AcademicInstitution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("LastUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(GETDATE())");

                    b.Property<DateOnly?>("LiquidationStartDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Phone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<string>("WWW")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("liquidationDate")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("AcademicInstitution_pk");

                    b.HasIndex("ParentId");

                    b.HasIndex("TypeId");

                    b.ToTable("AcademicInstitution", (string)null);
                });

            modelBuilder.Entity("DivisionStreet", b =>
                {
                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<int>("StreetId")
                        .HasColumnType("int");

                    b.HasKey("DivisionId", "StreetId");

                    b.HasIndex("StreetId");

                    b.ToTable("DivisionStreet");
                });

            modelBuilder.Entity("Application.DatabaseRelational.Models.Addresses.Address", b =>
                {
                    b.HasOne("Application.DatabaseRelational.Models.Addresses.Division", "Division")
                        .WithMany("Addresses")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Address_Division");

                    b.HasOne("Application.DatabaseRelational.Models.Addresses.Street", "Street")
                        .WithMany("Addresses")
                        .HasForeignKey("StreetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("Address_Street");

                    b.Navigation("Division");

                    b.Navigation("Street");
                });

            modelBuilder.Entity("Application.DatabaseRelational.Models.Addresses.Division", b =>
                {
                    b.HasOne("Application.DatabaseRelational.Models.Addresses.Country", "Country")
                        .WithMany("Divisions")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Country_Division");

                    b.HasOne("Application.DatabaseRelational.Models.Addresses.DivisionType", "DivisionType")
                        .WithMany("Divisions")
                        .HasForeignKey("DivisionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("DivisionType_Division");

                    b.HasOne("Application.DatabaseRelational.Models.Addresses.Division", "ParentDivision")
                        .WithMany("ChildDivisions")
                        .HasForeignKey("ParentDivisionId")
                        .HasConstraintName("Division_Division");

                    b.Navigation("Country");

                    b.Navigation("DivisionType");

                    b.Navigation("ParentDivision");
                });

            modelBuilder.Entity("Application.DatabaseRelational.Models.Addresses.Street", b =>
                {
                    b.HasOne("Application.DatabaseRelational.Models.Addresses.Country", "Country")
                        .WithMany("Streets")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Country_Street");

                    b.HasOne("Application.DatabaseRelational.Models.Addresses.DivisionType", "DivisionType")
                        .WithMany("Streets")
                        .HasForeignKey("DivisionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("DivisionType_Street");

                    b.Navigation("Country");

                    b.Navigation("DivisionType");
                });

            modelBuilder.Entity("Application.DatabaseRelational.Models.HighSchools.Institutions.AINameHistory", b =>
                {
                    b.HasOne("Application.DatabaseRelational.Models.HighSchools.Institutions.AcademicInstitution", "Institution")
                        .WithMany("NameHistories")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("AINameHistory_AcademicInstitution");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("Application.DatabaseRelational.Models.HighSchools.Institutions.AISpecificTypeHistory", b =>
                {
                    b.HasOne("Application.DatabaseRelational.Models.HighSchools.Institutions.AcademicInstitution", "Institution")
                        .WithMany("SpecificTypeHistories")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("AISpecificTypeHistory_AcademicInstitution");

                    b.HasOne("Application.DatabaseRelational.Models.HighSchools.Institutions.AISpecificType", "Type")
                        .WithMany("Histories")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("AISpecificTypeHistory_AISpecificType");

                    b.Navigation("Institution");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Application.DatabaseRelational.Models.HighSchools.Institutions.AIStatusHistory", b =>
                {
                    b.HasOne("Application.DatabaseRelational.Models.HighSchools.Institutions.AcademicInstitution", "Institution")
                        .WithMany("StatusHistories")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("AIStatusHistory_AcademicInstitution");

                    b.HasOne("Application.DatabaseRelational.Models.HighSchools.Institutions.AIStatus", "Status")
                        .WithMany("Histories")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("AIStatusHistory_AIStatus");

                    b.Navigation("Institution");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Application.DatabaseRelational.Models.HighSchools.Institutions.AcademicInstitution", b =>
                {
                    b.HasOne("Application.DatabaseRelational.Models.HighSchools.Institutions.AcademicInstitution", "ParentInstitution")
                        .WithMany("ChildInstitutions")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("AcademicInstitution_AcademicInstitution");

                    b.HasOne("Application.DatabaseRelational.Models.HighSchools.Institutions.AIType", "Type")
                        .WithMany("Institutions")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("AIType_AcademicInstitution");

                    b.Navigation("ParentInstitution");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("DivisionStreet", b =>
                {
                    b.HasOne("Application.DatabaseRelational.Models.Addresses.Division", null)
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DivisionStreet_DivisionId");

                    b.HasOne("Application.DatabaseRelational.Models.Addresses.Street", null)
                        .WithMany()
                        .HasForeignKey("StreetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DivisionStreet_StreetId");
                });

            modelBuilder.Entity("Application.DatabaseRelational.Models.Addresses.Country", b =>
                {
                    b.Navigation("Divisions");

                    b.Navigation("Streets");
                });

            modelBuilder.Entity("Application.DatabaseRelational.Models.Addresses.Division", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("ChildDivisions");
                });

            modelBuilder.Entity("Application.DatabaseRelational.Models.Addresses.DivisionType", b =>
                {
                    b.Navigation("Divisions");

                    b.Navigation("Streets");
                });

            modelBuilder.Entity("Application.DatabaseRelational.Models.Addresses.Street", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Application.DatabaseRelational.Models.HighSchools.Institutions.AISpecificType", b =>
                {
                    b.Navigation("Histories");
                });

            modelBuilder.Entity("Application.DatabaseRelational.Models.HighSchools.Institutions.AIStatus", b =>
                {
                    b.Navigation("Histories");
                });

            modelBuilder.Entity("Application.DatabaseRelational.Models.HighSchools.Institutions.AIType", b =>
                {
                    b.Navigation("Institutions");
                });

            modelBuilder.Entity("Application.DatabaseRelational.Models.HighSchools.Institutions.AcademicInstitution", b =>
                {
                    b.Navigation("ChildInstitutions");

                    b.Navigation("NameHistories");

                    b.Navigation("SpecificTypeHistories");

                    b.Navigation("StatusHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
