using Application.DatabaseRelational.Models.HighSchools.Courses;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Infrastructure.DatabaseRelational.Configurations.HighSchools.Courses
{
    public class IscedEFConfiguration : IEntityTypeConfiguration<Isced>
    {
        public void Configure(EntityTypeBuilder<Isced> builder)
        {
            builder.ToTable(nameof(Isced));
            builder.HasKey(x => x.Code).HasName($"{nameof(Isced)}_pk");

            builder.Property(x => x.Code);
            builder.Property(x => x.Name).HasMaxLength(200);

            builder.HasMany(x => x.Courses)
                .WithOne(x => x.Isced)
                .HasForeignKey(x => x.IscedCode)
                .HasConstraintName($"{nameof(Course)}_{nameof(Isced)}")
                .OnDelete(DeleteBehavior.Restrict);

            Isced[] items =
            {
                new Isced{ Code = "00", Name = "Grupa Programy ogólne" },
                new Isced{ Code = "000", Name = "Podgrupa programów i kwalifikacji ogólnych nieokreślonych dalej" },
                new Isced{ Code = "0000", Name = "Programy i kwalifikacje ogólne nieokreślone dalej" },
                new Isced{ Code = "001", Name = "Podgrupa programów i kwalifikacji podstawowych" },
                new Isced{ Code = "0011", Name = "Podstawowe programy i kwalifikacje" },
                new Isced{ Code = "002", Name = "Podgrupa umiejętności czytania, pisania i liczenia" },
                new Isced{ Code = "0021", Name = "Umiejętność czytania, pisania i liczenia" },
                new Isced{ Code = "003", Name = "Podgrupa rozwoju umiejętności osobowościowych" },
                new Isced{ Code = "0031", Name = "Rozwój umiejętności osobowościowych" },
                new Isced{ Code = "009", Name = "Podgrupa programów i kwalifikacji ogólnych gdzie indziej niesklasyfikowanych" },
                new Isced{ Code = "0099", Name = "Programy i kwalifikacje ogólne, gdzie indziej niesklasyfikowane" },
                new Isced{ Code = "01", Name = "Grupa Kształcenie" },
                new Isced{ Code = "011", Name = "Podgrupa pedagogiczna" },
                new Isced{ Code = "0110", Name = "Kształcenie nieokreślone dalej" },
                new Isced{ Code = "0111", Name = "Kształcenie" },
                new Isced{ Code = "0112", Name = "Kształcenie nauczycieli nauczania przedszkolnego" },
                new Isced{ Code = "0113", Name = "Kształcenie nauczycieli bez specjalizacji tematycznej" },
                new Isced{ Code = "0114", Name = "Kształcenie nauczycieli ze specjalizacją tematyczną" },
                new Isced{ Code = "0119", Name = "Kształcenie gdzie indziej niesklasyfikowane" },
                new Isced{ Code = "018", Name = "Podgrupa interdyscyplinarnych programów i kwalifikacji związanych z edukacją" },
                new Isced{ Code = "0188", Name = "Interdyscyplinarne programy i kwalifikacje związane z edukacją" },
                new Isced{ Code = "02", Name = "Grupa Nauki humanistyczne i sztuka" },
                new Isced{ Code = "020", Name = "Podgrupa programów i kwalifikacji związanych ze sztuką i przedmiotami humanistycznymi nieokreślonymi dalej" },
                new Isced{ Code = "0200", Name = "Programy i kwalifikacje związane ze sztuką i przedmiotami humanistycznymi nieokreślone dalej" },
                new Isced{ Code = "021", Name = "Podgrupa artystyczna" },
                new Isced{ Code = "0210", Name = "Programy i kwalifikacje związane ze sztuką nieokreślone dalej" },
                new Isced{ Code = "0211", Name = "Techniki audiowizualne i produkcja mediów" },
                new Isced{ Code = "0212", Name = "Moda, wystrój wnętrz i projektowanie przemysłowe" },
                new Isced{ Code = "0213", Name = "Sztuki plastyczne" },
                new Isced{ Code = "0214", Name = "Rękodzieło" },
                new Isced{ Code = "0215", Name = "Muzyka i sztuki sceniczne" },
                new Isced{ Code = "0219", Name = "Programy i kwalifikacje związane ze sztuką gdzie indziej niesklasyfikowane" },
                new Isced{ Code = "022", Name = "Podgrupa humanistyczna (z wyłączeniem języków)" },
                new Isced{ Code = "0220", Name = "Przedmioty humanistyczne (z wyłączeniem języków) nie określone dalej" },
                new Isced{ Code = "0221", Name = "Religia i teologia" },
                new Isced{ Code = "0222", Name = "Historia i archeologia" },
                new Isced{ Code = "0223", Name = "Filozofia i etyka" },
                new Isced{ Code = "0229", Name = "Przedmioty humanistyczne (z wyłączeniem języków) gdzie indziej niesklasyfikowane" },
                new Isced{ Code = "023", Name = "Podgrupa językowa" },
                new Isced{ Code = "0230", Name = "Języki nie określone dalej" },
                new Isced{ Code = "0231", Name = "Nauka języków" },
                new Isced{ Code = "0232", Name = "Literatura i językoznawstwo (lingwistyka)" },
                new Isced{ Code = "0239", Name = "Programy i kwalifikacje związane z językami gdzie indziej niesklasyfikowane" },
                new Isced{ Code = "028", Name = "Podgrupa interdyscyplinarnych programów i kwalifikacji związanych ze sztuką i przedmiotami humanistycznymi" },
                new Isced{ Code = "0288", Name = "Interdyscyplinarne programy i kwalifikacje obejmujące sztuki i przedmioty humanistyczne" },
                new Isced{ Code = "029", Name = "Podgrupa programów i kwalifikacji związanych ze sztuką i przedmiotami humanistycznymi gdzie indziej niesklasyfikowanymi" },
                new Isced{ Code = "0299", Name = "Programy i kwalifikacje związane ze sztuką i przedmiotami humanistycznymi gdzie indziej niesklasyfikowane" },
                new Isced{ Code = "03", Name = "Grupa Nauki społeczne, dziennikarstwo i informacja" },
                new Isced{ Code = "030", Name = "Podgrupa nauk społecznych, dziennikarstwa i informacji nieokreślonych dalej" },
                new Isced{ Code = "0300", Name = "Nauki społeczne, dziennikarstwo i informacja nieokreślone dalej" },
                new Isced{ Code = "031", Name = "Podgrupa społeczna" },
                new Isced{ Code = "0310", Name = "Nauki społeczne nieokreślone dalej" },
                new Isced{ Code = "0311", Name = "Ekonomia" },
                new Isced{ Code = "0312", Name = "Politologia i wiedza o społeczeństwie" },
                new Isced{ Code = "0313", Name = "Psychologia" },
                new Isced{ Code = "0314", Name = "Socjologia i kulturoznawstwo" },
                new Isced{ Code = "0319", Name = "Programy i kwalifikacje związane z naukami społecznymi, gdzie indziej niesklasyfikowane" },
                new Isced{ Code = "032", Name = "Podgrupa dziennikarstwa i informacji" },
                new Isced{ Code = "0320", Name = "Dziennikarstwo i informacja naukowa nieokreślone dalej" },
                new Isced{ Code = "0321", Name = "Dziennikarstwo" },
                new Isced{ Code = "0322", Name = "Bibliotekoznawstwo, informacja naukowa i archiwistyka" },
                new Isced{ Code = "0329", Name = "Dziennikarstwo i informacja naukowa gdzie indziej niesklasyfikowane" },
                new Isced{ Code = "038", Name = "Podgrupa interdyscyplinarnych programów i kwalifikacji związanych z naukami społecznymi, dziennikarstwem i informacją" },
                new Isced{ Code = "0388", Name = "Interdyscyplinarne programy i kwalifikacje związane z naukami społecznymi, dziennikarstwem i informacją" },
                new Isced{ Code = "039", Name = "Podgrupa nauk społecznych, dziennikarstwa i informacji gdzie indziej niesklasyfikowanych" },
                new Isced{ Code = "0399", Name = "Nauki społeczne, dziennikarstwo i informacja gdzie indziej niesklasyfikowane" },
                new Isced{ Code = "04", Name = "Grupa Biznes, administracja i prawo" },
                new Isced{ Code = "040", Name = "Podgrupa biznesu, administracji i prawa nieokreślonych dalej" },
                new Isced{ Code = "0400", Name = "Biznes, administracja i prawo nieokreślone dalej" },
                new Isced{ Code = "041", Name = "Podgrupa biznesu i administracji" },
                new Isced{ Code = "0410", Name = "Biznes i administracja nie określone dalej" },
                new Isced{ Code = "0411", Name = "Rachunkowość i podatki" },
                new Isced{ Code = "0412", Name = "Finanse, bankowość i ubezpieczenia" },
                new Isced{ Code = "0413", Name = "Zarządzanie i administracja" },
                new Isced{ Code = "0414", Name = "Marketing i reklama" },
                new Isced{ Code = "0415", Name = "Prace sekretarskie i biurowe" },
                new Isced{ Code = "0416", Name = "Sprzedaż hurtowa i detaliczna" },
                new Isced{ Code = "0417", Name = "Umiejętności związane z miejscem pracy" },
                new Isced{ Code = "0419", Name = "Programy i kwalifikacje związane z prowadzeniem działalności gospodarczej i administracją gdzie indziej niesklasyfikowane" },
                new Isced{ Code = "042", Name = "Podgrupa prawna" },
                new Isced{ Code = "0421", Name = "Prawo" },
                new Isced{ Code = "048", Name = "Podgrupa interdyscyplinarnych programów i kwalifikacji związanych z prowadzeniem działalności gospodarczej, administracją i prawem" },
                new Isced{ Code = "0488", Name = "Interdyscyplinarne programy i kwalifikacje związane z prowadzeniem działalności gospodarczej, administracją i prawem" },
                new Isced{ Code = "049", Name = "Podgrupa programów i kwalifikacji związanych z prowadzeniem działalności gospodarczej, administracją i prawem gdzie indziej niesklasyfikowanych" },
                new Isced{ Code = "0499", Name = "Programy i kwalifikacje obejmujące prowadzenie działalności gospodarczej, administrację i prawo gdzie indziej niesklasyfikowane" },
                new Isced{ Code = "05", Name = "Grupa Nauki przyrodnicze, matematyka i statystyka" },
                new Isced{ Code = "050", Name = "Podgrupa nauk przyrodniczych, matematyki i statystyki nieokreślonych dalej" },
                new Isced{ Code = "0500", Name = "Nauki przyrodnicze, matematyka i statystyka nieokreślone dalej" },
                new Isced{ Code = "051", Name = "Podgrupa biologiczna" },
                new Isced{ Code = "0510", Name = "Nauki biologiczne i powiązane nieokreślone dalej" },
                new Isced{ Code = "0511", Name = "Biologia" },
                new Isced{ Code = "0512", Name = "Biochemia" },
                new Isced{ Code = "0519", Name = "Programy i kwalifikacje związane z biologią i naukami pokrewnymi gdzie indziej niesklasyfikowane" },
                new Isced{ Code = "052", Name = "Podgrupa nauk o środowisku" },
                new Isced{ Code = "0520", Name = "Nauki o środowisku nieokreślone dalej" },
                new Isced{ Code = "0521", Name = "Ekologia i ochrona środowiska" },
                new Isced{ Code = "0522", Name = "Środowisko naturalne i przyroda" },
                new Isced{ Code = "0529", Name = "Programy i kwalifikacje związane ze środowiskiem gdzie indziej niesklasyfikowane" },
                new Isced{ Code = "053", Name = "Podgrupa fizyczna" },
                new Isced{ Code = "0530", Name = "Nauki fizyczne nieokreślone dalej" },
                new Isced{ Code = "0531", Name = "Chemia" },
                new Isced{ Code = "0532", Name = "Nauki o Ziemi" },
                new Isced{ Code = "0533", Name = "Fizyka" },
                new Isced{ Code = "0539", Name = "Programy i kwalifikacje związane z naukami fizycznymi gdzie indziej niesklasyfikowane" },
                new Isced{ Code = "054", Name = "Podgrupa matematyczna i statystyczna" },
                new Isced{ Code = "0540", Name = "Matematyka i statystyka nieokreślone dalej" },
                new Isced{ Code = "0541", Name = "Matematyka" },
                new Isced{ Code = "0542", Name = "Statystyka" },
                new Isced{ Code = "058", Name = "Podgrupa interdyscyplinarnych programów i kwalifikacji obejmujących nauki przyrodnicze, matematykę i statystykę" },
                new Isced{ Code = "0588", Name = "Interdyscyplinarne programy i kwalifikacje obejmujące nauki przyrodnicze, matematykę i statystykę" },
                new Isced{ Code = "059", Name = "Podgrupa nauk przyrodniczych, matematyki i statystyki gdzie indziej niesklasyfikowanych" },
                new Isced{ Code = "0599", Name = "Nauki przyrodnicze, matematyka i statystyka gdzie indziej niesklasyfikowane" },
                new Isced{ Code = "06", Name = "Grupa Technologie teleinformacyjne" },
                new Isced{ Code = "061", Name = "Podgrupa technologii teleinformacyjnych" },
                new Isced{ Code = "0610", Name = "Technologie teleinformacyjne nieokreślone dalej" },
                new Isced{ Code = "0611", Name = "Obsługa i użytkowanie komputerów" },
                new Isced{ Code = "0612", Name = "Projektowanie i administrowanie baz danych i sieci" },
                new Isced{ Code = "0613", Name = "Tworzenie i analiza oprogramowania i aplikacji" },
                new Isced{ Code = "0619", Name = "Technologie teleinformacyjne gdzie indziej niesklasyfikowane" },
                new Isced{ Code = "068", Name = "Podgrupa interdyscyplinarnych programów i kwalifikacji obejmujących technologie informacyjno-komunikacyjne" },
                new Isced{ Code = "0688", Name = "Interdyscyplinarne programy i kwalifikacje obejmujące technologie informacyjno-komunikacyjne" },
                new Isced{ Code = "07", Name = "Grupa Technika, przemysł, budownictwo" },
                new Isced{ Code = "070", Name = "Podgrupa techniki, przemysłu i budownictwa nieokreślonych dalej" },
                new Isced{ Code = "0700", Name = "Technika, przemysł i budownictwo nieokreślone dalej" },
                new Isced{ Code = "071", Name = "Podgrupa inżynieryjno-techniczna" },
                new Isced{ Code = "0710", Name = "Inżynieria i zawody inżynieryjne nieokreślone dalej" },
                new Isced{ Code = "0711", Name = "Inżynieria chemiczna i procesowa" },
                new Isced{ Code = "0712", Name = "Technologie związane z ochroną środowiska" },
                new Isced{ Code = "0713", Name = "Elektryczność i energia" },
                new Isced{ Code = "0714", Name = "Elektronika i automatyka" },
                new Isced{ Code = "0715", Name = "Mechanika i metalurgia" },
                new Isced{ Code = "0716", Name = "Pojazdy samochodowe, statki i samoloty" },
                new Isced{ Code = "0719", Name = "Inżynieria i zawody inżynierskie gdzie indziej niesklasyfikowane" },
                new Isced{ Code = "072", Name = "Podgrupa produkcji i przetwórstwa" },
                new Isced{ Code = "0720", Name = "Produkcja i przetwórstwo nieokreślone dalej" },
                new Isced{ Code = "0721", Name = "Przetwórstwo żywności" },
                new Isced{ Code = "0722", Name = "Surowce (szkło, papier, tworzywo sztuczne i drewno)" },
                new Isced{ Code = "0723", Name = "Tekstylia (odzież, obuwie i wyroby skórzane)" },
                new Isced{ Code = "0724", Name = "Górnictwo i wydobycie" },
                new Isced{ Code = "0729", Name = "Programy i kwalifikacje związane z przetwórstwem przemysłowym gdzie indziej niesklasyfikowane" },
                new Isced{ Code = "073", Name = "Podgrupa architektury i budownictwa" },
                new Isced{ Code = "0730", Name = "Architektura i budownictwo nieokreślone dalej" },
                new Isced{ Code = "0731", Name = "Architektura i planowanie przestrzenne" },
                new Isced{ Code = "0732", Name = "Budownictwo i inżynieria lądowa i wodna" },
                new Isced{ Code = "078", Name = "Podgrupa interdyscyplinarnych programów i kwalifikacji obejmujących technikę, przemysł i budownictwo" },
                new Isced{ Code = "0788", Name = "Interdyscyplinarne programy i kwalifikacje obejmujące technikę, przemysł i budownictwo" },
                new Isced{ Code = "079", Name = "Podgrupa techniki, przemysłu i budownictwa gdzie indziej niesklasyfikowanych" },
                new Isced{ Code = "0799", Name = "Technika, przemysł i budownictwo gdzie indziej niesklasyfikowane" },
                new Isced{ Code = "08", Name = "Grupa Rolnictwo" },
                new Isced{ Code = "080", Name = "Rolnictwo, leśnictwo, rybołówstwo i weterynaria nieokreślone dalej" },
                new Isced{ Code = "0800", Name = "Rolnictwo, leśnictwo, rybołówstwo i weterynaria nieokreślone dalej" },
                new Isced{ Code = "081", Name = "Podgrupa rolnicza" },
                new Isced{ Code = "0810", Name = "Rolnictwo nieokreślone dalej" },
                new Isced{ Code = "0811", Name = "Produkcja roślinna i zwierzęca" },
                new Isced{ Code = "0812", Name = "Ogrodnictwo" },
                new Isced{ Code = "0819", Name = "Programy i kwalifikacje związane z rolnictwem gdzie indziej niesklasyfikowane" },
                new Isced{ Code = "082", Name = "Podgrupa leśna" },
                new Isced{ Code = "0821", Name = "Leśnictwo" },
                new Isced{ Code = "083", Name = "Podgrupa rybactwa" },
                new Isced{ Code = "0831", Name = "Rybactwo" },
                new Isced{ Code = "084", Name = "Podgrupa weterynaryjna" },
                new Isced{ Code = "0841", Name = "Weterynaria" },
                new Isced{ Code = "088", Name = "Podgrupa interdyscyplinarnych programów i kwalifikacji obejmujących rolnictwo, leśnictwo, rybactwo i weterynarię" },
                new Isced{ Code = "0888", Name = "Interdyscyplinarne programy i kwalifikacje obejmujące rolnictwo, leśnictwo, rybactwo i weterynarię" },
                new Isced{ Code = "089", Name = "Podgrupa rolnictwa, leśnictwa, rybactwa i weterynaria gdzie indziej niesklasyfikowanych" },
                new Isced{ Code = "0899", Name = "Rolnictwo, leśnictwo, rybactwo i weterynaria gdzie indziej niesklasyfikowane" },
                new Isced{ Code = "09", Name = "Grupa Zdrowie i opieka społeczna" },
                new Isced{ Code = "090", Name = "Podgrupa zdrowia i opieki społecznej nieokreślonych dalej" },
                new Isced{ Code = "0900", Name = "Zdrowie i opieka społeczna nieokreślone dalej" },
                new Isced{ Code = "091", Name = "Podgrupa medyczna" },
                new Isced{ Code = "0910", Name = "Zdrowie nieokreślone dalej" },
                new Isced{ Code = "0911", Name = "Stomatologia" },
                new Isced{ Code = "0912", Name = "Medycyna" },
                new Isced{ Code = "0913", Name = "Pielęgniarstwo i położnictwo" },
                new Isced{ Code = "0914", Name = "Technologie związane z diagnostyką i leczeniem" },
                new Isced{ Code = "0915", Name = "Terapia i rehabilitacja" },
                new Isced{ Code = "0916", Name = "Farmacja" },
                new Isced{ Code = "0917", Name = "Medycyna i terapia tradycyjna oraz komplementarna" },
                new Isced{ Code = "0919", Name = "Zdrowie gdzie indziej niesklasyfikowane" },
                new Isced{ Code = "092", Name = "Podgrupa opieki społecznej" },
                new Isced{ Code = "0920", Name = "Opieka społeczna nieokreślona dalej" },
                new Isced{ Code = "0921", Name = "Opieka nad osobami starszymi i dorosłymi niepełnosprawnymi" },
                new Isced{ Code = "0922", Name = "Usługi związane z opieką nad dziećmi i młodzieżą" },
                new Isced{ Code = "0923", Name = "Praca socjalna i doradztwo" },
                new Isced{ Code = "0929", Name = "Opieka społeczna gdzie indziej niesklasyfikowana" },
                new Isced{ Code = "098", Name = "Podgrupa interdyscyplinarnych programów i kwalifikacji obejmujących zdrowie i opiekę społeczną" },
                new Isced{ Code = "0988", Name = "Interdyscyplinarne programy i kwalifikacje obejmujące zdrowie i opiekę społeczną" },
                new Isced{ Code = "099", Name = "Podgrupa zdrowie i opieka społeczna gdzie indziej niesklasyfikowane" },
                new Isced{ Code = "0999", Name = "Zdrowie i opieka społeczna gdzie indziej niesklasyfikowane" },
                new Isced{ Code = "10", Name = "Grupa Usługi" },
                new Isced{ Code = "100", Name = "Podgrupa usług nieokreślonych dalej" },
                new Isced{ Code = "1000", Name = "Usługi nieokreślone dalej" },
                new Isced{ Code = "101", Name = "Podgrupa usług dla ludności" },
                new Isced{ Code = "1010", Name = "Usługi dla ludności nieokreślone dalej" },
                new Isced{ Code = "1011", Name = "Usługi domowe" },
                new Isced{ Code = "1012", Name = "Pielęgnacja włosów i urody" },
                new Isced{ Code = "1013", Name = "Hotele, restauracje i katering" },
                new Isced{ Code = "1014", Name = "Sport" },
                new Isced{ Code = "1015", Name = "Turystyka i wypoczynek" },
                new Isced{ Code = "1019", Name = "Programy i kwalifikacje związane z usługi dla ludności gdzie indziej niesklasyfikowane" },
                new Isced{ Code = "102", Name = "Podgrupa higieny i bezpieczeństwa pracy" },
                new Isced{ Code = "1020", Name = "Usługi higieny i bezpieczeństwa pracy nieokreślone dalej" },
                new Isced{ Code = "1021", Name = "Higiena publiczna" },
                new Isced{ Code = "1022", Name = "Bezpieczeństwo i higiena pracy" },
                new Isced{ Code = "1029", Name = "Programy i kwalifikacje związane z usługami w zakresie higieny i bezpieczeństwa pracy" },
                new Isced{ Code = "103", Name = "Podgrupa ochrony i bezpieczeństwa" },
                new Isced{ Code = "1030", Name = "Ochrona i bezpieczeństwo nieokreślone dalej" },
                new Isced{ Code = "1031", Name = "Wojsko i obronność" },
                new Isced{ Code = "1032", Name = "Ochrona osób i mienia" },
                new Isced{ Code = "1039", Name = "Programy i kwalifikacje związane z ochroną i bezpieczeństwem gdzie indziej niesklasyfikowane" },
                new Isced{ Code = "104", Name = "Podgrupa usług transportowych" },
                new Isced{ Code = "1041", Name = "Transport" },
                new Isced{ Code = "108", Name = "Podgrupa interdyscyplinarnych programów i kwalifikacji obejmujących usługi" },
                new Isced{ Code = "1088", Name = "Interdyscyplinarne programy i kwalifikacje obejmujące usługi" },
                new Isced{ Code = "109", Name = "Podgrupa usług gdzie indziej niesklasyfikowanych" },
                new Isced{ Code = "1099", Name = "Usługi gdzie indziej niesklasyfikowane" },
                new Isced{ Code = "99", Name = "Grupa Obszar nieznany" },
                new Isced{ Code = "999", Name = "Podgrupa obszar nieznany" },
                new Isced{ Code = "9999", Name = "Obszar nieznany" }
                };

            builder.HasData(items);
        }
    }
}
